[general]

; Set default context 
; ^^^^^^^^^^^^^^^^^^^
;
; OPTIONS request are periodically sent by SBC for health checking
; purposes. We should return a 200 OK instead of 404 Not Found. The
; 404 happened because context 'default' was being search in 
; extensions.conf since the configuration 'context' wasn't set in
; [general] section.

allowguest=no
context=sip-telephonix
subscribecontext=sip-telephonix
externip=152.67.8.223
localnet=10.5.6.10/255.255.255.0
session-timers=refuse
tlsenable=yes
tlscertfile=/etc/asterisk/keys/asterisk.pem
tlscafile=/etc/asterisk/keys/ca.crt
tlsdontverifyserver=yes
;port=5060

; Registration expiry
; ^^^^^^^^^^^^^^^^^^^
rtptimeout=120
rtpholdtimeout=600
tlsenable=yes
tlscertfile=/etc/asterisk/keys/asterisk.pem
tlscafile=/etc/asterisk/keys/ca.crt
tlsdontverifyserver=yes
; The default registration expiry for asterisk is 120 seconds but 
; some SBC prefer it to be higher. In such a case the following
; error is shown
;
;   Got 423 Interval too brief for service 67927000@10.0.74.2, minimum is 300 seconds 
;
; Do note, asterisk will automatically use the minimum specified
; above and re-register so no change is required. However, for 
; correctness purposes, we set the default expiry to 15 minutes.

;ID-LOCAL-TATAMEDIA-TELKOM
[qasbc.exotel.com]
type=friend
host=13.215.201.160
port=5062
;The new name for the 'username' variable.
;defaultuser=320732
;secret=exotel_320732
disallow=all
allow=ulaw
allow=alaw
dtmfmode=rfc2833
nat=no
;bindport=5060
;Starting with Asterisk v1.6.0: The previously deprecated options "insecure=very" and "insecure=yes" have now been removed. "insecure=invite,port" is the equivalent of "insecure=very"
insecure=invite,port
transport=udp
canreinvite=no
context=sip-telephonix
sendrpid=yes
trustrpid=yes
relaxdtmf=yes
qualify=yes
qualifyfreq=20

[pstn.mum1.exotel.com]
host=129.154.231.198
port=443
type=friend
disallow=all
allow=alaw,ulaw
fromdomain=pstn.mum1.exotel.com
transport=tls
nat=yes
context=incoming
insecure=invite,port
qualify=yes
qualifyfreq=15
encryption=yes

[ipplatform]
host=13.215.201.160
port=5062
type=friend
disallow=all
allow=alaw
allow=ulaw
fromdomain=veeno-ts.exotel.in
transport=udp
nat=yes
context=voip
insecure=invite,port
transport=udp
qualify=yes
qualifyfreq=15
directmedia=no
trustrpid=yes 
sendrpid=yes

[app2app]
host=13.215.201.160
port=5062
type=friend
disallow=all
allow=alaw
allow=ulaw
fromdomain=veeno-ts.exotel.in
transport=udp
nat=yes
context=voip
insecure=invite,port
transport=udp
qualify=yes
qualifyfreq=15
directmedia=no
trustrpid=yes 
sendrpid=yes

[eptest]
host=152.67.2.17
port=443
type=friend
disallow=all
allow=alaw,ulaw
fromdomain=pstn.mum1.exotel.com
transport=tls
nat=yes
context=incoming
insecure=invite,port
qualify=yes
qualifyfreq=15
encryption=yes


[streamtrunksgp1] (streaming)
host=streaming-servers.exotel.com
type=friend
fromuser=calltrunk
qualify=yes
port=5060

[streamtrunkmum1] (streaming)
host=streaming-servers.mum1.exotel.com
type=friend
fromuser=calltrunk
qualify=yes
port=5060

[securestreamtrunksgp1]
host=streaming-servers.exotel.com
type=friend
port=443
disallow=all
allow=ulaw
allow=alaw
dtmfmode=rfc2833
nat=no
canreinvite=yes
context=from-streamtrunk
sendrpid=yes
trustrpid=yes
relaxdtmf=yes
qualify=yes
qualifyfreq=5
encryption=yes
transport=tls

[securestreamtrunkmum1]
host=streaming-servers.mum1.exotel.com
type=friend
port=443
disallow=all
allow=ulaw
allow=alaw
dtmfmode=rfc2833
nat=no
canreinvite=yes
context=from-streamtrunk
sendrpid=yes
trustrpid=yes
relaxdtmf=yes
qualify=yes
qualifyfreq=5
encryption=yes
transport=tls